### ISSUE TITLE
Install without docker-compose

### ISSUE THREAD

**Issue by JamesDAdams** [vsellier/easy-cozy#14]
Hi, i'm on unraid OS, so i don't want use docker-compose.

I correctly install db and cozy container,

i correctly execute the init.sh command like this : 
![image](https://user-images.githubusercontent.com/20860324/189538811-2d5228ef-cb2d-414a-8ffa-262f26705b44.png)

But i have a problem with create-instance.sh : i try the first command like this :

```
docker exec Cozy ./cozy instances add --host 0.0.0.0 --apps registry,drive,collect,settings,onboarding "jamesadams.cozy.domain.com" | tee "/tmp/cozyXXX"
```
But the terminal response this : 
```
Could not get password from standard input: EOF
```

You have an idea ?

**Comment by vsellier** [comment]
Hi James,

Is a COZY_ADMIN_PASSPHRASE environment variable is well defined in your docker container ?
It will be used to create the `/etc/cozy/cozy-admin-passphrase` during startup.

As a workaround, you can launch the command directly in you container, it should prompt for your admin password
```
docker exec Cozy bash
./cozy instances add --host 0.0.0.0 --apps registry,drive,collect,settings,onboarding "jamesadams.cozy.domain.com" 
```
