### ISSUE TITLE
Setup with sslh and nginx [Guide]

### ISSUE THREAD

**Issue by moookino** [vsellier/easy-cozy#2]
Hello Vincent,
very appreciated to your work and creating this setup instructions, but i have problem running this solution in combination with sslh and nginx, because i'm also using Streisand effect solution to host some vpn things, i'm a kind a newbee in this things, but want to use your solution :)

Is it possible to improve your guide with describing how to bypass nginx and use in combination with sslh?

Thanks in advance!

**Comment by vsellier** [comment]
closed due to too long inactivity.
Unfortunately, I'm not familiar with sslh., feel to reopen or propose a PR if you have found a solution.
