### ISSUE TITLE
Can't install on openmediavault

### ISSUE THREAD

**Issue by millionart** [vsellier/easy-cozy#3]
The port 80 has been used by OMV.

**Comment by millionart** [comment]
changed ports, still not work at all, too many errors:

Could not fetch manifest for registry://onboarding/stable: registry: version not found

Failed to install onboarding: Application manifest is not reachable"

SSL_ERROR_RX_RECORD_TOO_LONG 

@vsellier

**Comment by vsellier** [comment]
Hi @millionart 
Could you explain the changes on the configuration you have made and the command you have issued ?
You have given me too little information to understand and reproduce the problem.

**Comment by millionart** [comment]
Sorry, I finally gave up cozy after some trade-offs. It has too few functions.
