### ISSUE TITLE
volume name is too short

### ISSUE THREAD

**Issue by gerisse** [vsellier/easy-cozy#4]
Hi,
a issue when i launch with docker -compose the stack :  
_ERROR: for front  Cannot create container for service front: create .: volume name is too short_
This error appears when the script creates the volume  `easy-cozy_front_1`
An idea ?
Thanks

**Comment by vsellier** [comment]
it looks like you have not created an ``.env`` file to configure where your data will be stored.

You can do it by copying the [env.template](https://github.com/vsellier/easy-cozy/blob/master/env.template) file.
Of course, You can adapt the values for your needs.

I hope this will help.

**Comment by mikael-s** [comment]
Thanks for your work!
I had the same issue because the `ACME_DIRECTORY` variable was not defined in the `.env` file. Maybe that line could be added in the `README`?

**Comment by vsellier** [comment]
Sure you are right, it was missing on the example.
