### ISSUE TITLE
install on NAS

### ISSUE THREAD

**Issue by gerisse** [vsellier/easy-cozy#7]
hi
i try to install iton my nas : i created a env file. but , at the start, the cli says : 
```
[/share/homes/rp/git/easy-cozy] # docker-compose up -d
WARNING: The DATABASE_DIRECTORY variable is not set. Defaulting to a blank string.
WARNING: The COZY_TLD variable is not set. Defaulting to a blank string.
WARNING: The STORAGE_DIRECTORY variable is not set. Defaulting to a blank string.
WARNING: The ACME_DIRECTORY variable is not set. Defaulting to a blank string.
Creating easy-cozy_db_1    ... error
Creating easy-cozy_front_1 ... 
Creating easy-cozy_front_1 ... error

ERROR: for easy-cozy_front_1  Cannot create container for service front: create .: volume name is too short, names should be at least two alphanumeric characters
```
an idea ?
thanks for your work

**Comment by vsellier** [comment]
Hi @gerisse,

Could you paste the output of an `ls -al` and the content of your `.env` file (with any sensitive value obfuscated off course ;) )
Could you also precise which linux distribution and version of docker/docker-compose is running on your NAS?

Thanks

**Comment by gerisse** [comment]
ls -al :

            drwxrwx--- 7 gerisse   everyone       4096 2021-04-18 18:05 ./
            drwxrwx--- 3 admin administrators 4096 2021-04-18 18:01 ../
            -rwxrwx--- 1 gerisse   everyone        908 2021-04-17 13:42 application.sh*
            drwxrwx--- 2 gerisse   everyone       4096 2021-04-17 13:42 build/
            drwxrwx--- 2 gerisse   everyone       4096 2021-04-17 13:42 config/
            drwxrwx--- 2 gerisse   everyone       4096 2021-04-17 13:42 cozystack/
            -rwxrwx--- 1 gerisse   everyone        942 2021-04-17 13:42 create-instance.sh*
            -rw-rw---- 1 gerisse   everyone         72 2021-04-17 13:42 docker-compose-arm.yml
            -rw-rw---- 1 gerisse   everyone       1320 2021-04-17 13:42 docker-compose.yml
            -rw-rw---- 1 gerisse   everyone        659 2021-04-18 18:03 env
            -rw-rw---- 1 gerisse   everyone        657 2021-04-17 13:42 env.template
            drwxrwx--- 8 gerisse   everyone       4096 2021-04-17 13:42 .git/
            -rw-rw---- 1 gerisse   everyone          9 2021-04-17 13:42 .gitignore
            -rwxrwx--- 1 gerisse   everyone        143 2021-04-17 13:42 init.sh*
            drwxrwx--- 2 gerisse   everyone       4096 2021-04-17 13:42 kubernetes/
            -rw-rw---- 1 gerisse   everyone       3623 2021-04-17 13:42 README.md

content of env : 

                # The place to store the database content
                DATABASE_DIRECTORY=/var/lib/cozy/db
                # The place to store the cozy's raw files
                STORAGE_DIRECTORY=/var/lib/cozy/storage
                # The place to store the let's encrypt stuff
                ACME_DIRECTORY=/var/lib/acme
                # The base domain used for the cozy cloud instances
                COZY_TLD=********
                # The contact email used for let's encrypt
                EMAIL=************
                # The admin passphrase
                COZY_ADMIN_PASSPHRASE=**********

docker-compose version 1.27.4, build 40524192
Docker version 20.10.3, build c52c09e6b8
Linux NAS-251 4.14.24-qnap #1 SMP Wed Apr 28 01:48:08 CST 2021 x86_64 GNU/Linux

**Comment by garcia-dev** [comment]
Hi @gerisse, 

I'm just passing by but viewing the result of your `ls -al`, I would say that cozy is expecting a `.env` file and yours is just `env`. Rename your `env` file to `.env` and it should be ok.

**Comment by gerisse** [comment]
oh yes ... : it s ok
thanks
