### ISSUE TITLE
Konnector support

### ISSUE THREAD

**Issue by nitnelave** [vsellier/easy-cozy#9]
Hey!

I looked into this image to get my cozy up and running, but sadly the lack of connectors is a bit blocking for me.

Having a look at the way you set up the image, you seem to do it from an archive. Any reason you're doing it this way, and not through the debian/ubuntu package manager? (recommended installation way at https://docs.cozy.io/en/tutorials/selfhost-debian/)

From what I understand, using the packages would lower the maintenance burden of this image and add support for konnectors.

**Comment by vsellier** [comment]
Hi,
Yes, the dependencies of the `cozy-stack` / `cozy` packages are too important.
It seems the packages are designed for an all-in-one server installation (it pulls couchdb/niginx/...), it makes sense for a basic installation, but it's not the way it's used here as couch and nginx are running in dedicated containers.

Regarding the konnectors support, I'm not sure to understand what is your problem.
The apps/konnectors are working on the images both via the command line or via cozy-store.

**Comment by nitnelave** [comment]
That's fair.

Note: if the konnectors are supported, it might make sense to correct the Readme that says that they aren't :)

The reason why I thought that they weren't is that when I tried to run the Boursorama one, I got:

```
Stderr: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module cozy-konnector-libs
Require stack:
- /tmp/konnector-boursorama567143635/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/konnector-boursorama567143635/src/index.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: MODULE_NOT_FOUND,
  requireStack: [ /tmp/konnector-boursorama567143635/src/index.js ]
}
```

Would you know what that is about?

**Comment by vsellier** [comment]
thanks, I will check that.

The readme probably needs a refact as there are some stuff from the early beginning, and to be honest, I didn't create new instances every days.

Feel free to propose a PR if you find/think something can be improved there.

**Comment by vsellier** [comment]
btw, not directly related to the error, but, AFAIK, cozy-banks is not working on on-premise installation as it needs using a third-party broker (except for the credit-agricole connector)

https://support.cozy.io/article/302-budget-insight

**Comment by vsellier** [comment]
I don't get the error, for example, the ameli or netflix konnectors also used the cozy-konnector-libs and are orrectly working on my instance.
I've also checked with the default install you've mentioned and I can't see anything relative to this lib.
Perhaps it's due to the way it's installed as as far I can see, it's not available directly on the cozy-store.

**Comment by vsellier** [comment]
(I will not dig further on this problem as it seems it's not directly relative to the installation)
